### ISSUE TITLE
Infura is missing events sometimes

### ISSUE THREAD

**Issue by olaf89** [INFURA/infura#50] opened 2018-01-06 13:30 UTC
With the same get_logs parameters, different number of events is returned. FromBlock and ToBlock are constant and are in the past. I tested is also agains etherscan API which always returns same result.

Here is reproduced:
https://stackblitz.com/edit/angular-2aowai?file=app%2Fapp.component.ts

**Comment by tueric** [comment] 2018-02-23 02:52
Gunna close this since its a duplicate of #51. Future updates will be there.

**Closed by tueric** 2018-02-23 02:52 UTC
