### ISSUE TITLE
CORS error when calling API

### ISSUE THREAD

**Issue by pwrstudio** [INFURA/infura#57] opened 2018-01-17 21:16 UTC
When calling 
`https://api.infura.io/v1/jsonrpc/rinkeby/eth_call?params=%5B%7B%0D%0A%09%09"to"%3A%20"0x737A4FA0eDBcc8c29d74cd2cebA315314E2C608A"%2C%0D%0A%09%09"data"%3A%20"0x6d4ce63c"%0D%0A%09%7D%2C%0D%0A%09"latest"%0D%0A%5D` from a vue.js app I get the following error: 
```
No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access.
```
Accessing the URL in chrome or postman works – and the call from the vue app was working yesterday! In fact, looking at the response in dev tools shows that body contains the excepted result of the contract method call, and the status is 200, but the call still fails, perhaps due to a missing `Access-Control-Allow-Origin` header in the response.

I have tried setting a header on the request like so:
```
Vue.http.headers.common['Access-Control-Allow-Origin'] = '*'
```
This causes a OPTIONS call to be made before the GET call, but this fails with a 405 status.

**Request headers for GET call**
```
:authority:api.infura.io
:method:GET
:path:/v1/jsonrpc/rinkeby/eth_call?params=%5B%7B%0D%0A%09%09%22to%22%3A%20%220x737A4FA0eDBcc8c29d74cd2cebA315314E2C608A%22%2C%0D%0A%09%09%22data%22%3A%20%220x6d4ce63c%22%0D%0A%09%7D%2C%0D%0A%09%22latest%22%0D%0A%5D
:scheme:https
accept:application/json, text/plain, */*
accept-encoding:gzip, deflate, br
accept-language:sv,en-US;q=0.9,en;q=0.8,de;q=0.7,da;q=0.6,nl;q=0.5
dnt:1
origin:http://localhost:8080
referer:http://localhost:8080/stack
user-agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
```

**Response headers for GET call**
```
accept-ranges:bytes
age:0
content-encoding:gzip
content-length:138
content-type:application/json
date:Wed, 17 Jan 2018 21:10:28 GMT
fastly-debug-digest:f89d5cffbe910a1431760e1ba646c75479030e010cd006ab5a7f83e550e675fe
status:200
vary:Accept-Encoding
via:1.1 varnish
via:1.1 varnish
x-cache:MISS, MISS
x-cache-hits:0, 0
x-served-by:cache-iad2144-IAD, cache-hhn1541-HHN
x-timer:S1516223429.763915,VS0,VE115
```

**Comment by nieroda** [comment] 2018-01-18 06:29
app.use(cors());

**Comment by pwrstudio** [comment] 2018-01-18 09:01
I am making the call client-side. I suppose one solution would be to proxy the request, but would prefer not to.

**Comment by maurycyp** [comment] 2018-01-19 17:37
Folks, this should be fixed now.

**Comment by maurycyp** [comment] 2018-01-19 18:26
Please let me know if you see any CORS issues again.

**Closed by maurycyp** 2018-01-19 18:26 UTC

**Comment by asghaier76** [comment] 2018-02-08 21:58
Is this solved, I am using web3js and using infura as the provider, when I try to watch for an event I receive the same error.

**Comment by appielife** [comment] 2018-07-31 06:36
@maurycyp 
 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*
while calling eth.getTransactionCount

**Comment by appielife** [comment] 2018-07-31 07:32
![image](https://user-images.githubusercontent.com/13350207/43444642-eaca3494-94c1-11e8-8c9d-e4f36a932952.png)

**Comment by ZyanWlayor** [comment] 2018-08-04 09:43
emm,I've had this problem.Then I downgrade web3 to 1.0.0-beta.34,and there's no problem.

**Comment by SarsTW** [comment] 2018-08-13 03:48
Hi @ZyanWlayor and @nachomazzara 

According to https://github.com/ethereum/web3.js/releases/tag/v1.0.0-beta.35

A breaking change at 1.0.0-beta.35.

Need to use following code instead

```
var options = {
    timeout: 20000, // milliseconds,
    headers: [{name: 'Access-Control-Allow-Origin', value: '*'},{...}]
};
var http = new Web3HttpProvider('http://localhost:8545', options);
```

**Comment by jurosh** [comment] 2018-08-16 13:57
Similar CORS issue (strange that only in Firefox) here with `0.20.7`, downgrade to `0.19.1` helped.

**Comment by jparklev** [comment] 2018-08-29 22:17
I'm facing the same issue, any word on this?

**Comment by idpsycho** [comment] 2018-11-06 18:31
Can anyone point to the web3 issue being resolved? We are experiencing CORS Safari problem with infura. Access-control-allow-origin is set to *, but safari requires it to be set to request host. Going back to older version is nice quickfix but doesn't really address the cause and the resolution.
@ZyanWlayor @mikheevm

**Comment by idpsycho** [comment] 2018-11-06 18:48
This is probably the web3 issue causing it: https://github.com/ethereum/web3.js/issues/1802
While the infura has some imperfect headers, the problem appears only when withCredentials is used as explained in the thread.

**Comment by settltoshi** [comment] 2018-12-16 20:36
My firefox install for whatever reason sends `Access-Control-Request-Headers: content-type,user-agent`. In that case infura doesnt send cors headers in response. Request w/o `user-agent` works as expected.

**Comment by AlberErre** [comment] 2019-01-04 21:06
Similar CORS error here, just while using `0.20.6` on Firefox or Safari. Chrome has no issues.

Just solved it downgrading to `0.19.1` 👍

**Comment by L-F-Escobar** [comment] 2019-01-16 02:42
I am having the same issue using "web3": "^1.0.0-beta.26" on Firefox v64.0

Any fix for this??

**Comment by dillonsvincent** [comment] 2019-03-24 00:00
I'm also seeing this issue in beta.50 version. Works in chrome but throws cors error in firefox. I don't want to downgrade because I'm using tuples in my contracts so either way I move the version something won't work.

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://rinkeby.infura.io/v3/51c7a53bafa248xxxx31fbd3fcd624f7. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing)

**Comment by devstein** [comment] 2019-03-30 16:22
Also seeing this on Firefox and Safari using  `"web3": "1.0.0-beta.37"`

**Comment by barrard** [comment] 2019-04-07 01:17
> Also seeing this on Firefox and Safari using `"web3": "1.0.0-beta.37"`

Me too, but only on my mobile device, works on desktop.

![coors](https://user-images.githubusercontent.com/11924470/55677194-06d19480-587f-11e9-9256-04bf5f56c496.png)

**Comment by marsrobertson** [comment] 2019-04-25 23:26
> Failed to load resource: the server responded with a status of 400 (Bad Request)
> upload-infura.html:1 Access to fetch at 'http://ipfs.infura.io:5001/api/v0/add?stream-channels=true' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

### Here is my super simple demo

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Infura IPFS CORS issue</title>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.js"></script>
    <script src="https://unpkg.com/ipfs-http-client@30.1.3/dist/index.js"></script>
    <script src="https://bundle.run/buffer@5.2.1"></script>

  </head>
  <body>

  	<h3>readAsArrayBuffer to Buffer to Infura to IPFS</h3>
  	<input type="file" id="upload">

  	<script>
  		const ipfs = window.IpfsHttpClient('ipfs.infura.io', '5001')

  		$("#upload").on("change", function() {
	        var reader = new FileReader();
	        reader.onload = function (e) {

	        	const magic_array_buffer_converted_to_buffer = buffer.Buffer(reader.result); // honestly as a web developer I do not fully appreciate the difference between buffer and arrayBuffer 

				    ipfs.add(magic_array_buffer_converted_to_buffer, (err, ipfsHash) => {
		        	console.log(err,ipfsHash);
		      	})
	        }
	        reader.readAsArrayBuffer(this.files[0]);
  		})
  	</script>
  
  </body>
</html>
```

I'm always supporting simplicity and wider adoption. I'm not that good programmer, that's why my code must be simple. See also: https://github.com/jschiarizzi/storj-ipfs-gateway/issues/9#issuecomment-486852922 _(really trying to get IPFS up and running)_

**Comment by bellaj** [comment] 2019-07-01 22:04
vanished once IE used

**Comment by miguelmota** [comment] 2019-07-25 15:44
Same problem on Safari

<img width="842" alt="Screen Shot 2019-07-25 at 8 44 22 AM" src="https://user-images.githubusercontent.com/168240/61888714-deff4e80-aeb8-11e9-8096-0f3fb7b521fc.png">
