### ISSUE TITLE
Infura provide WS (websocket) support?

### ISSUE THREAD

**Issue by oxy-coin** [INFURA/infura#37] opened 2017-10-20 13:24 UTC
Like infura providing RPC. are they providing WS support also ? I have developed my Dapp using nodejs so want to user websocket as web3.

**Comment by icaroharry** [comment] 2017-10-20 17:50
Duplicate of #29

**Comment by egalano** [comment] 2017-11-04 00:04
Please track this via #29

**Closed** 2017-11-04 00:04 UTC
