### ISSUE TITLE
Does Infura support the Web3.js 1.0 API?

### ISSUE THREAD

**Issue by lukehedger** [INFURA/infura#29] opened 2017-08-11 09:35 UTC
Using `web3@1.0.0-beta.18` I have attempted to deploy a contract to Rinkeby with a single argument:
```
myContract.deploy({ arguments: [ 123 ] })
```

The contract deploys OK but when calling a method to return the constructor argument, `0` is returned, which suggests the argument was not processed.
```
myContract.methods.echo().call({ from: fromAccount })
  .then( res => console.log(res) ) //=> 0
```

The contract is here for ref:
```
pragma solidity ^0.4.0;

contract Echo {
  uint value;

  function Echo(uint _value) {
    value = _value;
  }

  function echo() constant returns (uint) {
    return value;
  }
}
```

**Comment by egalano** [comment] 2017-09-08 18:23
Hi @lukehedger we're working on web3.js 1.0 support i.e. scalable websocket support now. It's in early alpha support stage on our side. If you're interested in helping us test it out shoot me your contact info and I'll get you access.

**Comment by lukehedger** [comment] 2017-09-12 09:21
Hey @egalano - sounds cool! Would definitely like to help test. Email is: luke@jaak.io.

**Comment by rhlsthrm** [comment] 2017-09-26 17:55
Hi @egalano, I'd also like to test out the new version. Email is rahul@connextapi.com.

**Comment by tensor5** [comment] 2017-10-02 10:08
Hi @egalano, I'd like to try the Web3.js 1.0 support. tensor5@gmail.com. Thanks

**Comment by strelok1** [comment] 2017-10-06 01:16
Would love to get beta access to web3js 1.0 support with web sockets. roman.rodov+github@gmail.com

**Comment by rhlsthrm** [comment] 2017-10-06 06:00
Has anyone gotten an email from them regarding this issue? I have not received anything.

**Comment by egalano** [comment] 2017-10-06 14:59
Sorry for the delay, I just sent the email with the connection details. Please give it a try and let us know if you encounter any issues.

**Comment by strelok1** [comment] 2017-10-06 15:14
Thanks. Got the email. Will report back with any probs. Cheers

**Comment by tensor5** [comment] 2017-10-06 15:36
@egalano Thanks!

**Comment by DalderupMaurice** [comment] 2017-10-09 11:39
Any estimation when this functionality will be available? 
Currently, I have no clue how to watch events whatsoever - while using infura. @egalano

**Comment by miguelmota** [comment] 2017-10-10 22:05
@egalano i'm interested in trying out and testing infura websocket support miguel@mota.email

**Comment by samandarr** [comment] 2017-10-11 07:36
Hi @egalano, happy to test out the alpha version.  Email: ravshanoff at protonmail

**Comment by valashnez** [comment] 2017-10-12 05:25
Hi @egalano , I'd also love to test out the alpha version. Email: cvaladez@stanford.edu

**Comment by jdkanani** [comment] 2017-10-12 07:22
@egalano Hey I have built infra to listen live events from Ethereum: https://matic.network/dagger
Thought you would find this interesting.

**Comment by miguelmota** [comment] 2017-10-12 08:03
Really cool library @jdkanani

**Comment by egalano** [comment] 2017-10-12 18:16
Nice @jdkanani . Is that library compatible with any Ethereum node or specifically Geth's pub-sub API.

**Comment by jdkanani** [comment] 2017-10-12 18:26
@egalano Unfortunately no.

Problem was that - if you have multiple Geth nodes - you have to deploy filters on every node. Plus, separating filters from Geth will give you  more control over filter types. There are some cons too. But overall this will make development very easy for DApps.

**Comment by icaroharry** [comment] 2017-10-13 13:14
hey @egalano. I'm trying to listen to an event (with Web3.js) from a contract deployed in Ropsten but I'm getting `The current provider doesn't support subscriptions`. Is it related to this issue? If so, I'm interested in testing the websocket support. Email: me@icaro.io

Thanks in advance!

**Comment by egalano** [comment] 2017-10-13 23:24
Hi @icaroharry yes our API does not allow stateful requests at the moment. Our JSONRPC API endpoint currently load balances requests between many backend Ethereum nodes to be able to handle our large request volume. This is why we don't allow event subscriptions which use eth_newFilter and eth_getFilterLogs. Typically people are using eth_getLogs method and polling to be able to simulate the behavior of an event subscription. Or you can try out our websocket endpoint which we have been working on which should finally deliver this desired feature to users.

**Comment by jdkanani** [comment] 2017-10-14 03:06
@icaroharry How did you solve this problem then?

**Comment by carlolm** [comment] 2017-10-14 22:48
@egalano hi can I try out websocket beta also? I am working on a DApp requiring real time event updates. Thanks! carlol@gmail.com

**Comment by icaroharry** [comment] 2017-10-16 13:42
@jdkanani I'm working on an alpha version of a DApp, so temporarily I implemented a good old "refresh button" that calls `web3.contract.getPastEvents` :smile:

Now I'm going to test the websockets. Kudos to @egalano

**Comment by jdkanani** [comment] 2017-10-16 15:45
@icaroharry Great. And, @egalano what did you change at Infura to solve problem of "installing same filters on all nodes"?

**Comment by bshevchenko** [comment] 2017-10-21 08:09
Hi @egalano, I'd also like to test out the new version! Email is info@bshevchenko.ru

**Comment by MisterDr** [comment] 2017-10-21 21:23
Hi @egalano, could you please add me to WS beta at: djenadrazic@gmail.com. Thank you :)

**Comment by LefterisJP** [comment] 2017-10-22 15:02
Hey @egalano could I get beta acces to websocket support? lefteris@refu.co

**Comment by afiorenza** [comment] 2017-10-24 01:05
Hi @egalano do you have an ETA for this? Thank you.

**Comment by afiorenza** [comment] 2017-10-24 01:05
Hi @egalano Do you have an ETA for this? Thank you

**Comment by oxy-coin** [comment] 2017-10-24 14:17
Hey @egalano  .. Please send me details also i would love to be alpha tester for this. Thanks. anilbaweja.bx@gmail.com

**Comment by hbwoodrose** [comment] 2017-10-24 23:00
i would also love to get some of that sweet websocket access. please add meeee!!!! :D max@daashaus.com

Thanks!

**Comment by alexey-ernest** [comment] 2017-10-25 09:11
Hi @egalano I wonna try websocket also. Thanks. alexey.ernest@gmail.com

**Comment by plachira** [comment] 2017-10-25 23:34
Hi @egalano Can you please add me in beta testing of WS? binoy@plachira.com Thanks.

**Comment by eugeneotto** [comment] 2017-11-01 16:26
Hi @egalano, I'd love to try Infura's websocket transport, as well. Thank you!

**Comment by nosuchip** [comment] 2017-11-02 15:36
Hi @egalano, could you please add me to tester pool? nosuchip@gmail.com. Thanks.

**Comment by netpi** [comment] 2017-11-05 09:21
Hi @egalano Can you please add me in beta testing of WS?  Thank you very much !

**Comment by okwme** [comment] 2017-11-05 21:25
Hi @egalano we spoke at EtherealSF about websocket support, is it possible to have access?

**Comment by dancre** [comment] 2017-11-08 04:49
Hi @egalano could you please add me to websocket beta testing also? dane.creighton@gmail.com. Thank you very much!

**Comment by andrewsource147** [comment] 2017-11-08 08:41
Hi @egalano  Could you please add me in WS? Thank you very much!
My email: andrew@kyber.network

**Comment by dlebrecht** [comment] 2017-11-08 13:04
@egalano can i have access to ws?

thanks

**Comment by egalano** [comment] 2017-11-08 17:00
Thanks for your patience everyone. We just sent out out another batch of invites to try this out. If you are already using our wss endpoints please send us feedback on how your experience is going. Thanks!

**Comment by C0deMunk33** [comment] 2017-11-09 00:57
I would also like access please. hollandcodeandgraphics at gmail

Thank you!

**Comment by amitranjan14** [comment] 2017-11-09 18:47
@egalano
 interested in checking out the new api's. would be thankful if you can provide the connection details on the mail id: ameetranjan at gmail dot com

**Comment by andrewsource147** [comment] 2017-11-10 09:06
@egalano Does INFURA supports websocket for KOVAN testnet?

**Comment by dschoeni** [comment] 2017-11-10 14:24
@egalano: could you send us an invite as well? d.schoeni[ät]papers.ch - very interested in this!

**Comment by AntonioJuliano** [comment] 2017-11-13 01:27
@egalano would love an invite to antonio@dydx.exchange

**Comment by zwalla** [comment] 2017-11-13 20:21
@egalano would really love to test with this tom@blocktech.com. could you send an invite?

**Comment by enriquefynn** [comment] 2017-11-13 21:38
Hi @egalano, can I get an invite? fynn@montelabs.com. Thanks

**Comment by amitranjan14** [comment] 2017-11-14 04:46
@egalano please do share the invites.

**Comment by tetsuo** [comment] 2017-11-16 14:29
Can I join too? ogunduz@gmail.com Thank you!

**Comment by ealmansi** [comment] 2017-11-16 20:59
Hi @egalano, I'd like to try out websocket support too if possible.
My email is: ealmansi@gmail.com
Thanks!

**Comment by Matko95** [comment] 2017-11-17 10:29
Hello guys, I'd like to test out the new library with our DApp, could I get an invite? mtrifunovski at gmail dot com

**Comment by tetsuo** [comment] 2017-11-17 10:43
@egalano Hey! can I get an invite?  ogunduz@gmail.com Thanks!

**Comment by Hu4F00d** [comment] 2017-11-17 16:39
HI @egalano I'm doing an app that requires live updates, can I get an invite? mauro@osn.global thanks a lot!

**Comment by chuacw** [comment] 2017-11-19 01:11
Hi @egalano Can I get an invite? Scanning blocks for transactions take way too long! chuacw a gmail com

**Comment by bitpshr** [comment] 2017-11-20 14:55
Could I please get an invite? paulbouchon90@gmail.com. Thanks!

**Comment by buhrmi** [comment] 2017-11-22 01:19
Hello @egalano me too, please: buhrmi@gmail.com

**Comment by artemii235** [comment] 2017-11-22 16:19
Hello @egalano. Please send me an invite too: ortgma@gmail.com. Does it work already on main net?

**Comment by decodedbrain** [comment] 2017-11-25 07:34
Hello @egalano. Please send me invite to WebSockets Infura access to decodemybrain@gmail.com

**Comment by sheraz104** [comment] 2017-11-25 22:02
Hello @egalano Kindly send me the invitation for infura WS support. sheraz1392@gmail.com

**Comment by pash7ka** [comment] 2017-11-27 02:22
Hi @egalano, I would like to try Infura WS support, please send me an invite. pash7ka+infura@gmail.com

**Comment by DomiDre** [comment] 2017-11-28 06:09
Hi @egalano are you still searching for beta testers for the web socket support? I would like an invitation homiedomi@gmail.com

**Comment by cheerfyt** [comment] 2017-12-01 03:25
Hi there, i want to sync some data (about my contracts) from infura.io to my local db, is there any way to do this? @egalano  can i get an invite? [cheerfyt@gmail.com](cheerfyt@gmail.com)

**Comment by trakout** [comment] 2017-12-06 03:00
@egalano If websocket support is still in testing, I'd love to receive an invite. Thanks! trakout@gmail.com

**Comment by pash7ka** [comment] 2017-12-06 03:04
I've never received any reply to my request, so it seems like this beta testing program is not running.

**Comment by ertugrulyilmaz** [comment] 2017-12-06 08:46
Hi @egalano, I would like to try Infura WS support, please send me an invite. ert.yil@gmail.com

**Comment by doexclusive** [comment] 2017-12-08 15:12
Hi @egalano , If it's possible please please grant me access to testing of Infura Websockets, my email is denig55amg@gmail.com

**Comment by Bryan792** [comment] 2017-12-08 21:09
If this is still running, I would like access Bryan792@gmail.com Thanks.

**Comment by vrolland** [comment] 2017-12-11 14:06
I am also very interested in. But, I would rather not put my email here.

Would be possible to get in touch?

**Comment by ZhiGuang** [comment] 2017-12-12 01:13
@egalano Can you send me an invitation? nrobot@outlook.com Thank you.

**Comment by eacolina** [comment] 2017-12-13 19:28
@egalano Can I get access to the beta too? eacolina@uwaterloo.ca Thanks!

**Comment by Hirama** [comment] 2017-12-18 16:19
@egalano Can I get access to the beta too? giorkin@gmail.com Many thanks!

**Comment by caa1982** [comment] 2017-12-19 17:12
Can I get access to the beta please? cyril@2getherbank.com thanks!

**Comment by wnz99** [comment] 2017-12-24 16:55
@egalano Could I please get access to the beta too? dfava80@gmail.com Thanks!

**Comment by tritao** [comment] 2017-12-27 18:02
Hi, can I get access? joao@tritao.eu

**Comment by johncpalmer** [comment] 2017-12-27 21:55
Hi, idk if this is getting to spammy at this point but, @egalano I would love access to the beta as well. Want to be able to subscribe to events. Thanks!

**Comment by ConnorGutman** [comment] 2018-01-01 19:10
@egalano If you're still accepting requests for the beta, could I possibly get access at connorgutman@gmail.com? Thank you and happy New Year! 🎉

**Comment by dellintosh** [comment] 2018-01-05 22:20
@egalano If you have any extra invitations for the beta testing I'd love to get one as well.  Thank you!

**Comment by adonley** [comment] 2018-01-07 01:09
@egalano same here, would love beta for this infura feature -> andrewjdonley@gmail.com . Thanks!

**Comment by capablemonkey** [comment] 2018-01-08 05:50
I'd also like to help test this! :)  technix1@gmail.com

**Comment by ryanschneider** [comment] 2018-01-08 16:40
Hey everyone, Ryan from Infura here.

Two updates.  First off, I'm targeting tomorrow morning (California time) to roll out a new version of our websocket infrastructure.  There shouldn't be any down time, but your existing sessions may time out.

This new version is more scalable, so after it's released I'll post the URLs for all 3 support networks, so you won't need an invite going forward.

Expect the upgrade to occur around 2017-01-09 17:00 UTC, about 24 hours from now.  If you see any issues after the rollout, please @-reply me instead of egalano.  Thanks!

**Comment by dmitryVonDrake** [comment] 2018-01-09 13:47
@egalano Hi! I'd also like to test this! dmitry8drak@gmail.com Thanks a lot!

**Comment by ryanschneider** [comment] 2018-01-09 17:19
The upgrade will be a little bit delayed but is still happening soon, I'll post here when the endpoints are cut over.

**Comment by ryanschneider** [comment] 2018-01-09 18:08
Ok all, the new endpoints are live and are accessible at:

```
wss://mainnet.infura.io/ws
wss://ropsten.infura.io/ws
wss://rinkeby.infura.io/ws
```

Again, at-reply me on this issue or create a new one if you run into any issues.

**Comment by buhrmi** [comment] 2018-01-09 19:16
Wow, amazing. Thanks so much for providing this...!!!

**Comment by dellintosh** [comment] 2018-01-09 20:15
@ryanschneider - first off, thank you for this!
I'm having some difficulties getting the new [batch requests](http://web3js.readthedocs.io/en/1.0/web3.html#batchrequest) to work properly, is that functionality available on these new endpoints?

**Comment by ryanschneider** [comment] 2018-01-09 23:11
Sorry for the delay @dellintosh, currently we do not support batch requests.  I'll add it to our road map to see if it's something we can support in a scalable manner.

**Comment by chuacw** [comment] 2018-01-10 02:33
@ryanschneider the new endpoints seem to be much much slower than before. Previously, my webpage retrieves data with the endpoint almost instantaneously (in the sense that data is shown so fast, I couldn't even see it crawl on the screen). Now, I can see the data crawling on the screen.

**Comment by ryanschneider** [comment] 2018-01-10 02:59
@chuacw which RPCs are you using?  Are these subscriptions or single RPC calls?

**Comment by maxidev** [comment] 2018-01-10 04:09
For web3 1.0 usage is there any other RPC url? or we can use: https://mainnet.infura.io/xhy**

**Comment by rhlsthrm** [comment] 2018-01-13 01:04
Getting the following error on Web3 1.0 when I try to call a contract function: 

`Error: Returned error: The method eth_sendTransaction does not exist/is not available`

Is sending transactions not supported through the INFURA nodes? I unlocked my account and can sign transactions properly.

**Comment by ryanschneider** [comment] 2018-01-13 01:17
No only `eth_sendRawTransaction` is supported.  `sendTransaction` would require us to have access to your private key.  You'll need to create and sign the tx locally and then send it via `eth_sendRawTransaction`.

See: https://github.com/INFURA/infura/wiki/FAQ

**Comment by rhlsthrm** [comment] 2018-01-13 01:30
@ryanschneider thanks for the quick response! I'm trying to interact with contracts through raw Web3. I did it through Truffle before with their abstraction, but now I am trying to use raw Web3. I'll have to see if there's a way to do it with the raw transaction.

**Comment by davidboom95** [comment] 2018-01-14 03:13
Hi, I would like to get Access to web socket url please 👍 
davidboom95@gmail.com

**Comment by eccheung4** [comment] 2018-01-15 06:01
@ryanschneider I'm getting this error when trying to use getPastEvents on the `wss://rinkeby.infura.io/ws`

```
Error: CONNECTION ERROR: Couldn't connect to node on IPC.
    at Object.InvalidConnection (/Users/eccheung4/Documents/Business/metax/adchain-registry-events-db/node_modules/web3-core-helpers/src/errors.js:35:16)
    at WebsocketProvider._timeout (/Users/eccheung4/Documents/Business/metax/adchain-registry-events-db/node_modules/web3-providers-ws/src/index.js:192:48)
    at W3CWebSocket.connection.onclose (/Users/eccheung4/Documents/Business/metax/adchain-registry-events-db/node_modules/web3-providers-ws/src/index.js:96:15)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/Users/eccheung4/Documents/Business/metax/adchain-registry-events-db/node_modules/yaeti/lib/EventTarget.js:107:17)
    at W3CWebSocket.onClose (/Users/eccheung4/Documents/Business/metax/adchain-registry-events-db/node_modules/websocket/lib/W3CWebSocket.js:228:10)
    at WebSocketConnection.<anonymous> (/Users/eccheung4/Documents/Business/metax/adchain-registry-events-db/node_modules/websocket/lib/W3CWebSocket.js:201:17)
    at emitTwo (events.js:125:13)
    at WebSocketConnection.emit (events.js:213:7)
    at WebSocketConnection.handleSocketClose (/Users/eccheung4/Documents/Business/metax/adchain-registry-events-db/node_modules/websocket/lib/WebSocketConnection.js:382:14)
    at emitOne (events.js:120:20)
    at TLSSocket.emit (events.js:210:7)
    at _handle.close (net.js:547:12)
    at TCP.done [as _onclose] (_tls_wrap.js:356:7)
```

Using code similar to this:
```
  const provider = `wss://rinkeby.infura.io/ws`
  let web3 = new Web3(new Web3.providers.WebsocketProvider(provider))
  let contract = new web3.eth.Contract(contractAbi, contractAddress);

  contract.getPastEvents('allEvents',
    {fromBlock: 0,  toBlock: 'latest'},
    (error, logs) => {
    if (error) console.error(error);
    logs.forEach(log => {
    	// Do something with log
    })
  })
```

**Comment by davidboom95** [comment] 2018-01-15 06:31
@eeccheung4 same problem here

**Comment by ryanschneider** [comment] 2018-01-15 17:00
@eccheung4 what happens if you use a smaller known block range (e.g. the first couple of blocks when you contract was published)?  I'm trying to diagnose where in the stack tis might be failing.

Thanks!

**Comment by eccheung4** [comment] 2018-01-15 17:44
@ryanschneider 
contract deployed at block 1168155, 
https://rinkeby.etherscan.io/tx/0x532120c88552b3598fccfa113fdccf1b0f3fd52888a9f714f380d8f1984d10cf

I tried setting fromBlock: 1168150, but got same error.

Related issue, but looks to be fixed for ropsten:
https://github.com/INFURA/infura/issues/54

**Comment by ryanschneider** [comment] 2018-01-15 18:37
@eccheung4 can you try this endpoint instead:

`wss://rinkeby.infura.io/_ws`

It's not as scalable of an endpoint, but is implemented slightly differently so would help me pinpoint what might be the cause.

**Comment by eccheung4** [comment] 2018-01-15 18:45
@ryanschneider yes, using that endpoint worked as before. I'm not getting that error anymore.

**Comment by DeRain** [comment] 2018-01-18 10:18
Hello @egalano, could you kindly send me access to ws endpoint? My email kirill.b@smartum.pro - thanks!

**Comment by eccheung4** [comment] 2018-01-18 17:16
@DeRain 

Links are public now:
```
wss://mainnet.infura.io/ws
wss://ropsten.infura.io/ws
wss://rinkeby.infura.io/ws
```

**Comment by MAVRO2** [comment] 2018-02-07 08:29
Hi all, i can't connect to infura's websocket 

`const provider = 'wss://mainnet.infura.io/ws';
let web3 = new Web3(new Web3.providers.WebsocketProvider(provider))
let contract = new web3.eth.Contract(abi, contractAddress);`

> connection not open on send()
Error: connection not open

**Comment by MAVRO2** [comment] 2018-02-12 10:25
Anybody here?

**Comment by egalano** [comment] 2018-02-13 02:13
@MAVRO2 I'm able to connect fine. Please use this script to test your setup:
```
#!/usr/bin/env node
const Web3 = require('web3');

const web3 = new Web3(new Web3.providers.WebsocketProvider('wss://mainnet.infura.io/ws'));

const subscription = web3.eth.subscribe('newBlockHeaders', (error, blockHeader) => {
  if (error) return console.error(error);

  console.log('Successfully subscribed!', blockHeader);
}).on('data', (blockHeader) => {
  console.log('data: ', blockHeader);
});

// unsubscribes the subscription
subscription.unsubscribe((error, success) => {
  if (error) return console.error(error);

  console.log('Successfully unsubscribed!');
});
```

**Comment by wnz99** [comment] 2018-02-13 07:42
Will Kovan be supported?

**Comment by egalano** [comment] 2018-02-13 10:36
We hope to support kovan too. It requires additional development work because the geth and parity subscription APIs are not compatible. Web3js actually only supports the geth subscription api at the moment so that is where we decided to start our efforts.

**Comment by StarNeit** [comment] 2018-02-13 18:18
Hello, everybody.

`const provider = 'wss://mainnet.infura.io/ws';
let web3 = new Web3(new Web3.providers.WebsocketProvider(provider))
let contract = new web3.eth.Contract(abi, contractAddress);

    contract.getPastEvents('allEvents',
        {fromBlock: 0,  toBlock: 'latest'},
        (error, logs) => {
            if (error) console.error(error);
            logs.forEach(log => {
                // Do something with log
                
            })
        })`

I am also getting this error.

**Error: CONNECTION ERROR: Couldn't connect to node on IPC.**

Any solution please.....

**Comment by jamboj** [comment] 2018-02-13 20:37
@egalano, 
Hi, thank you for posting the above code snippet - it does indeed work for me and runs without issues for hours.

However, when subscribing for events, I get **Connection dropped by remote peer.** disconnects every few minutes. 

My question is:
1) Is this normal/expected?
2) If not, do you immediately see anything wrong with my code or could it be node issue?
3) If yes, how can I handle this/resubscribe properly? 

Many thanks in advance.
Here is my code:

```
const Web3 = require('web3');
const web3 = new Web3(new Web3.providers.WebsocketProvider('wss://mainnet.infura.io/ws'));
var ckAddress = '0x06012c8cf97BEaD5deAe237070F9587f8E7A266d';
var ckABI = [{"constant":true,"inputs":<...>]
var ckContract = new web3.eth.Contract(ckABI, ckAddress);

var birthEvent = ckContract.events.Birth(eventHandler);

function eventHandler(error, result) {
        if(!error) { console.log("*** Kitty born:", result); }
        else { console.log("*** Birth event handler error", error); }
};
```

And the console output:

```
MacBook-Air:testdir testuser$ node testck.js 
*** Kitty born: { address: '0x06012c8cf97BEaD5deAe237070F9587f8E7A266d',
  blockNumber: 5084578,
<...>
     topics: 
      [ '0x0a5311bd2a6608f08a180df2ee7c5946819a649b204b554bb8e39825b2c50ad5' ] } }

```
etc, then the disconnect:

```
connection not open on send()
*** Birth event handler error _Event {
  type: 'close',
  isTrusted: false,
  _yaeti: true,
  code: 1006,
  reason: 'Connection dropped by remote peer.',
  wasClean: false,
  target: 
   W3CWebSocket {
     _listeners: {},
     addEventListener: [Function: _addEventListener],
     removeEventListener: [Function: _removeEventListener],
     dispatchEvent: [Function: _dispatchEvent],
     _url: 'wss://mainnet.infura.io/ws',
     _readyState: 3,
     _protocol: undefined,
     _extensions: [],
     _bufferedAmount: 0,
     _binaryType: 'arraybuffer',
     _connection: 
      WebSocketConnection {
        _debug: [Object],
        domain: null,
        _events: {},
        _eventsCount: 0,
        _maxListeners: undefined,
        _pingListenerCount: 0,
        config: [Object],
        socket: [Object],
        protocol: undefined,
        extensions: [],
        remoteAddress: '34.200.180.219',
        closeReasonCode: 1006,
        closeDescription: 'Connection dropped by remote peer.',
        closeEventEmitted: true,
        maskOutgoingPackets: true,
        maskBytes: <Buffer a0 78 ef 90>,
        frameHeader: <Buffer 81 7e 03 47 00 00 00 00 00 00>,
        bufferList: [Object],
        currentFrame: [Object],
        fragmentationSize: 0,
        frameQueue: [],
        connected: false,
        state: 'closed',
        waitingForCloseResponse: false,
        receivedEnd: true,
        closeTimeout: 5000,
        assembleFragments: true,
        maxReceivedMessageSize: 8388608,
        outputBufferFull: false,
        inputPaused: false,
        receivedDataHandler: [Function: bound ],
        _closeTimerHandler: [Function: bound ],
        webSocketVersion: 13,
        socketHadError: false },
     _client: 
      WebSocketClient {
        domain: null,
        _events: {},
        _eventsCount: 0,
        _maxListeners: undefined,
        config: [Object],
        _req: null,
        protocols: [],
        origin: undefined,
        url: [Object],
        secure: true,
        base64nonce: 'KmbbgDWMKyHgvjWfYhzvTA==',
        socket: [Object],
        response: [Object],
        firstDataChunk: null },
     onerror: [Function],
     onclose: [Function],
     onmessage: [Function] },
  cancelable: true,
  stopImmediatePropagation: [Function] }
MacBook-Air:testdir testuser$ 

```

**Comment by jamboj** [comment] 2018-02-13 22:54
debugging a bit more it seems the disconnect happens after exactly 5 mins of inactivity. I.e. no events for 5 mins -> Connection dropped by remote peer

so what's the best way to deal with this when watching a not very active contract?

**Comment by StarNeit** [comment] 2018-02-14 07:19
@ncocchiaro , Thank you.

I solved problem by using getTransactionReceipt. 👍 👍 👍

**Comment by StarNeit** [comment] 2018-02-14 13:13
Hi, @jamboj

**Comment by jamboj** [comment] 2018-02-14 17:29
Hi @StarNeit, 

My solution (although incomplete) is to subscribe to blocks like in @egalano's example above: this keeps communication with the peer up, however it is not bulletproof (i.e. if there's no blocks for 5+ mins, it will still disconnect) and also doesn't address a more general question of handling any disconnects/resubscribing.

Hope this helps, let me know if you have any follow up questions/need more detail

**Comment by egalano** [comment] 2018-02-14 17:51
Hi guys now that our websocket support is live I’m going to close this ticket so it doesn’t become a monolithic bug tracker for subscriptions. Please keep filing issues if you encounter them and we’ll take care of deduplicating tasks for our devs. Let’s start with creating a separate ticket for the issue where people are encountering websocket timeouts as that requires implementation of ping and pong messages in the websocket client and server per the Websocket RFC. https://tools.ietf.org/html/rfc6455

**Closed by egalano** 2018-02-14 17:51 UTC

**Comment by ericxtang** [comment] 2018-02-15 20:07
Question - should we add our own tokens to the URL?  I know it doesn't work right now, but what can we expect about that?

**Comment by ryanschneider** [comment] 2018-02-16 00:21
We will eventually provide a separate method for authenticating your account with web sockets, but haven't fully decided on the implementation yet, in the mean time no, you do not need to include your token on the URL.

**Comment by requilence** [comment] 2018-02-17 00:06
Do Infura's WS endpoints have some limitations? 
Looks like it just unexpectedly closes connection when I send a message **>4096bytes**
This is doesn't depends on the method (_eth_call_/_eth_estimateGas_/_eth_sendRawTransaction_)

The same calls succeed using the non-ws HTTPS RPC

**Comment by jchittoda** [comment] 2018-03-01 08:33
We are building an app @ ETHLend.io that would require Log Event listening. I saw that people have submitted their email ids to test WebSocket beta. Here is my email jitendra@ethlend.io if some info you think I should know. I see most of the information is already shared here. If something is not shared, please do shoot me email.
I am planning to use Web3j Java library as I am writing Java application. I need to see how this will be integrated with Web3j library.

**Comment by noprom** [comment] 2018-03-12 00:21
Hi, do you all solve your problems?
I also encountered this problem:
```
Error: CONNECTION ERROR: Couldn't connect to node on IPC.
    at Object.InvalidConnection (webpack-internal:///845:35:16)
    at WebsocketProvider._timeout (webpack-internal:///865:192:48)
    at WebSocket.connection.onclose (webpack-internal:///865:96:15)
From previous event:
    at PromiEvent (webpack-internal:///343:35:24)
    at send (webpack-internal:///52:446:21)
    at Object._executeMethod (webpack-internal:///860:819:24)
    at Object.method (webpack-internal:///87:44:66)
    at eval (webpack-internal:///87:487:22)
    at new Promise (<anonymous>)
    at new F (webpack-internal:///41:35:28)
    at Xflip.accessContractWithWeb3 (webpack-internal:///87:480:14)
    at eval (webpack-internal:///87:41:15)
    at new Promise (<anonymous>)
    at new F (webpack-internal:///41:35:28)
    at Xflip.getContractData (webpack-internal:///87:40:14)
    at Vue$3.initXflip (webpack-internal:///237:105:84)
    at Vue$3.boundFn [as initXflip] (webpack-internal:///7:192:12)
    at eval (webpack-internal:///237:82:13)
```

It works fine for `wss://ropsten.infura.io/ws` but `wss://mainnet.infura.io/ws` will throw this error.

**Comment by Plinpod** [comment] 2018-03-12 02:24
I'm having the exact same issue as @jamboj does anyone have a solution here?

**Comment by ericxtang** [comment] 2018-03-12 14:41
Yeah we had that problem too.  We ended up adding retry logic in our software - here the PR https://github.com/livepeer/go-livepeer/pull/320/files

**Comment by habdelra** [comment] 2018-03-12 18:49
@noprom @Plinpod have you tried using the `_ws` endpoint? like `wss://mainnet.infura.io/_ws`?

**Comment by Plinpod** [comment] 2018-03-12 18:59
@habdelra I did switch to the _ws endpoint and it seems more stable for me, however I do still get the same issues after it runs for awhile.

@ericxtang So with web3, I would basically just re-initialize the events everytime they error out?

**Comment by ericxtang** [comment] 2018-03-13 15:40
@Plinpod haven't tried in web3, but that seems reasonable (if initializing the event actually establishes a new connection).

@habdelra What's the difference between `/_ws` and `/ws`?

**Comment by ryanschneider** [comment] 2018-03-13 15:54
`/_ws` is our older endpoint that forwards straight to geth.  It's only suggested if you requiring batch support, and only then until we get batch support implemented in our proxy at `/ws`.

In general, you should code your websocket connection with the expectation that you will lose connectivity at some point and need to re-establish your subscriptions.  Whether using our shared endpoint or your own node, there will be times when maintenance or network connectivity issues occur and the connection needs to be terminated, so your code needs to handle re-connecting when that happens, and should re-subscribe to events it cares about.

I don't believe Geth's rpc/client module does not do this for you, so you need to add your own logic to resubscribe on top of it.

**Comment by guix77** [comment] 2018-03-16 10:58
Looking forward for progress on this

**Comment by ryan-rowland** [comment] 2018-03-24 02:33
I'm working on a WebSocket provider for MetaMask's Web3 1.0 provider (https://github.com/MetaMask/provider-engine/pull/227)

Running against `wss://ropsten.infura.io/ws`, `wss://rinkeby.infura.io/ws` and `wss://mainnet.infura.io/_ws` I'm getting normal behavior, a dropped connection every few minutes or so which is manageable.

However, on `wss://mainnet.infura.io/ws` I'm getting disconnected with `1006`s every few seconds. It's so frequent that I can't reliably get a response for my queries most of the time.

It was recommended that we point to `/ws` but the current behavior I'm observing isn't viable. Is there some specific reason I might be hitting such terrible connectivity here? Some thing I can change / accommodate for in my own code?

**Comment by ryanschneider** [comment] 2018-03-26 15:39
@ryan-rowland Can you open a separate issue instead of commenting on this closed one?  Please include some logs of RPC traffic that show the issue, specifically any traffic sent before the disconnects and the full JSONRPC payload for the `1006` error you are seeing.  Thanks!

**Comment by egalano** [comment] 2018-03-26 17:30
Hi folks, as mentioned above, we now support Web3js-1.0 subscriptions via websockets. If you are having any issues with our websocket feature please file a separate issue so we can better track and get it resolved. Locking this thread to keep things organized. Thanks!
