### ISSUE TITLE
Connect to Infura IPFS Node 

### ISSUE THREAD

**Issue by hermanjunge** [INFURA/infura#45] opened 2017-12-11 00:07 UTC
Reissuing this ticket here https://github.com/ipfs/js-ipfs-api/issues/642

cc @FedericoCapello @diasdavid

**Comment by ncocchiaro** [comment] 2018-02-28 21:53
@FedericoCapello we've made improvements to our gateway and this issue should be fixed, as the original poster can you please verify that it no longer occurs for you?

**Comment by jamesmorgan** [comment] 2018-03-02 19:39
Just tested and seems to work, only a basic `add` call on a directory e.g. https://ipfs.infura.io/ipfs/QmVro4TDR5bFkrVGa8zC4xdNNjdYXAcNqAGg9b8Xv643oP 

* node version `"ipfs-api": "^18.1.1"` 
* sample usage:
```
const ipfs = IPFS('ipfs.infura.io', '5001', {protocol: 'https'})

ipfs.add([...])
```

**Comment by FedericoCapello** [comment] 2018-03-04 16:02
It seems I can't publish, when I try to publish it gives me the following errors:

> POST https://ipfs.infura.io:5001/api/v0/name/publish?arg=QmWmo1gweztXxqaGv172VrmCr3cPmX5UA5ViuCgjWZV6P7&stream-channels=true 403 (Forbidden)

> Fetch API cannot load https://ipfs.infura.io:5001/api/v0/name/publish?arg=QmWmo1gweztXxqaGv172VrmCr3cPmX5UA5ViuCgjWZV6P7&stream-channels=true. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8888' is therefore not allowed access. The response had HTTP status code 403. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by ncocchiaro** [comment] 2018-03-28 01:07
Thanks for your patience. I think the issue is clearer to me now, and it has to do more with how we don't expose the /name API at the moment, rather than with CORS per se. We'll discuss internally about plans to open this up, also in light of the recent improvements to IPNS.

**Comment by gus-canya** [comment] 2018-05-21 12:49
@jamesmorgan may I see the code for this `ipfs.add` demo?

**Comment by jamesmorgan** [comment] 2018-05-23 13:47
@gus-canya sorry for the poor example but we use it like this:
```
const ipfs = IPFS('ipfs.infura.io', '5001', {protocol: 'https'});

function example(){
  return ipfs.add([
      {
        path: `my_ipfs_hash/image`,
        content: fs.createReadStream(`./config/data/ipfs_data/my_ipfs_hash/low_res.gif`),
      },
      {
        path: `my_ipfs_hash/description`,
        content: fs.createReadStream(`./config/data/ipfs_data/my_ipfs_hash/data`),
      }
    ], {recursive: false}
  )
}
```
We use node 8+, INFURA and have used IPFS extensively with our erc-721 assets and its working brilliantly

**Comment by eacolina** [comment] 2018-06-11 19:22
Just to be clear, as of now publishing a name to IPNS would not work through INFURA nodes since the latests IPNS improvements?

**Comment by ncocchiaro** [comment] 2018-06-12 00:31
We do not support the /name API on the public endpoint, so publishing to IPNS via that API through Infura would not work. This may change in the future, but we don't have detailed plans on this yet.

**Closed by ncocchiaro** 2018-06-12 00:31 UTC

**Comment by judasvennootschap** [comment] 2019-09-12 18:17
i get Cross-Origin Request Disabled when using http protocol, but it's work using https protocol.

**Comment by MichaelMure** [comment] 2019-09-12 18:29
We only support HTTPS for IPFS, not HTTP.
